Implement activity subscride method
group-life/core pull request #19
Opened 2021-09-07 17:08 UTC by Lehersun

Implement method that creates array of Activity\Visit objects

2021-09-07 17:19 UTC, Lehersun commented
How Activity :: subscribe can create an array [Activity => Visits]?
I could only think of this method to return an array [Visit]

2021-09-08 03:03 UTC, Magomogo requested changes

2021-09-08 03:03 UTC, Magomogo commented on src/Activity.php
> +    }
With such a public interface clients should know the internal implementation detail: you should not call `subscribe` until you do `setSchedule`. This is not good.

What do you think if we make `Schedule` object a mandatory dependency of an `Activity`? Requiring it in the constructor: an activity could never exists without its schedule, makes sense.

2021-09-08 03:03 UTC, Magomogo commented on src/Activity.php
> +        foreach ($this->schedule as $day) {
You could call `Schedule::materialize` here.

2021-09-08 03:03 UTC, Magomogo commented on src/Activity/Visit.php
> +    public function __construct(\DateTime $time, string $activity, Visitor $visitor)
Better depend on an object, it gives better abstraction and public interface for doing things. What is the reason you did that change with activity?

2021-09-08 03:05 UTC, Magomogo commented
> How Activity :: subscribe can create an array [Activity => Visits]?
> I could only think of this method to return an array [Visit]

Yes, it should give an array of Activity\Visit objects.

2021-09-08 07:55 UTC, Lehersun commented on src/Activity/Visit.php
> +    public function __construct(\DateTime $time, string $activity, Visitor $visitor)
So I have to create an ActivityVisit class?

2021-09-08 11:32 UTC, Magomogo commented on src/Activity/Visit.php
> +    public function __construct(\DateTime $time, string $activity, Visitor $visitor)
Just pass it here.

2021-09-08 11:56 UTC, Lehersun commented
Ready for check

2021-09-08 15:24 UTC, merged